baseURL = "https://www.bithues.com/"
locale = "en-us"
title = "Bithues"
contentDir = "hugo-src/content"
layoutDir = "hugo-src/layouts"
publishDir = "."
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    renderer = { unsafe = true }

[params]
  description = "Book reviews, reading guides, science fiction, fantasy, and original short stories."
