# Fusion 360 Python Script — Mortise and Tenon Block (Sample)
# Generated by: Bacotti Bot
# Purpose: Educational joinery block — Mortise and Tenon pair
# Units: centimeters (Fusion API requirement)
# For: P1S 3D printing with PLA/PETG

import adsk.core, adsk.fusion, traceback

def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        
        # Get active design
        product = app.activeProduct
        design = adsk.fusion.Design.cast(product)
        if not design:
            ui.messageBox('No active Fusion 360 design')
            return
        
        rootComp = design.rootComponent
        
        # ===== PARAMETERS (all in cm — 1cm = 10mm) =====
        BLOCK_SIZE = 2.0        # 20mm cube
        MORTISE_DEPTH = 0.8     # 8mm deep slot
        MORTISE_WIDTH = 0.6    # 6mm wide slot
        TENON_WIDTH = 0.58     # 5.8mm tenon (0.2mm gap for PLA tolerance)
        TENON_DEPTH = 0.82     # 8.2mm tenon (slightly proud for print fit)
        
        # ===== PART 1: MORTISE BLOCK (slot block) =====
        sketches = rootComp.sketches
        sketch1 = sketches.add(rootComp.xYConstructionPlane)
        lines1 = sketch1.sketchCurves.sketchLines
        
        # Draw slot rectangle centered on origin
        slot_half_w = MORTISE_WIDTH / 2
        slot_half_d = BLOCK_SIZE / 2
        
        lines1.addCenterPointRectangle(
            adsk.core.Point3D.create(0, 0, 0),
            adsk.core.Point3D.create(slot_half_w, slot_half_d, 0)
        )
        
        # Extrude as cut (pocket) — goes INTO the block
        prof1 = sketch1.profiles.item(0)
        extrudes1 = rootComp.features.extrudeFeatures
        extInput1 = extrudes1.createInput(
            prof1, 
            adsk.fusion.FeatureOperations.CutFeatureOperation
        )
        extInput1.setDistanceExtent(
            False, 
            adsk.core.ValueInput.createByReal(MORTISE_DEPTH)
        )
        extInput1.isSymmetric = False
        extrudes1.add(extInput1)
        
        # ===== PART 2: TENON BLOCK (plug block) =====
        # Second sketch offset from first
        offset = BLOCK_SIZE + TENON_DEPTH
        sketch2 = sketches.add(rootComp.xYConstructionPlane)
        lines2 = sketch2.sketchCurves.sketchLines
        
        # Draw tenon rectangle offset to the right
        tenon_half_w = TENON_WIDTH / 2
        tenon_half_d = BLOCK_SIZE / 2
        
        lines2.addCenterPointRectangle(
            adsk.core.Point3D.create(offset, 0, 0),
            adsk.core.Point3D.create(tenon_half_w, tenon_half_d, 0)
        )
        
        # Extrude as new body (protrusion)
        prof2 = sketch2.profiles.item(0)
        extInput2 = extrudes1.createInput(
            prof2,
            adsk.fusion.FeatureOperations.NewBodyFeatureOperation
        )
        extInput2.setDistanceExtent(
            False,
            adsk.core.ValueInput.createByReal(TENON_DEPTH)
        )
        extInput2.isSymmetric = False
        extrudes1.add(extInput2)
        
        # ===== NAMING =====
        bodies = rootComp.bRepBodies
        if bodies.count >= 2:
            bodies.item(0).name = 'Mortise_Block_20mm'
            bodies.item(1).name = 'Tenon_Plug_20mm'
        
        ui.messageBox(
            'Mortise & Tenon Block Pair Created!\n\n'
            'Mortise_Block_20mm: slot cut through face (center)\n'
            'Tenon_Plug_20mm: rectangular protrusion\n\n'
            'The tenon is 0.2mm smaller than the slot.\n'
            'Print two of each to test fit.\n\n'
            'Scale check: blocks are 20mm x 20mm x 20mm'
        )
        
    except:
        if ui:
            ui.messageBox('Error:\n{}'.format(traceback.format_exc()))


# ============================================================
# HOW TO USE THIS SCRIPT
# ============================================================
# Option A — Watched Folder (auto-run):
#   1. Fusion 360 → Scripts & Add-ins → My Scripts tab
#   2. Click watch folder icon → set to:
#      ~/openclaw/workspace/icloud/Bacotti Bot/3D-Printing/fusion-scripts/
#   3. Enable "Run automatically" in watched folder settings
#   4. Drop this .py file in the folder → auto-runs
#
# Option B — Manual:
#   1. Open Fusion 360
#   2. File → Scripts → My Scripts → "+" → add this file
#   3. Select script → click Run
#
# The model will appear in your design. Inspect it, then
# use Bambu Studio to slice and print.
